server:
  port: 80

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8675/eureka

spring:
  application:
    name: EurekaPublisher